
// 1. STYLES DATA (from original script.js)
// ============================================
let stylesByCategory = {
    love: [
        { name: "love_heart_1", prefix: "💖 ", suffix: " 💖", map: { a:"𝓪",b:"𝓫",c:"𝓬",d:"𝓭",e:"𝓮",f:"𝓯",g:"𝓰",h:"𝓱",i:"𝓲",j:"𝓳",k:"𝓴",l:"𝓵",m:"𝓶",n:"𝓷",o:"𝓸",p:"𝓹",q:"𝓺",r:"𝓻",s:"𝓼",t:"𝓽",u:"𝓾",v:"𝓿",w:"𝔀",x:"𝔁",y:"𝔂",z:"𝔃",A:"𝓐",B:"𝓑",C:"𝓒",D:"𝓓",E:"𝓔",F:"𝓕",G:"𝓖",H:"𝓗",I:"𝓘",J:"𝓙",K:"𝓚",L:"𝓛",M:"𝓜",N:"𝓝",O:"𝓞",P:"𝓟",Q:"𝓠",R:"𝓡",S:"𝓢",T:"𝓣",U:"𝓤",V:"𝓥",W:"𝓦",X:"𝓧",Y:"𝓨",Z:"𝓩" } },
        { name: "love_heart_2", prefix: "❤️ ", suffix: " ❤️", map: { a:"𝒶",b:"𝒷",c:"𝒸",d:"𝒹",e:"𝑒",f:"𝒻",g:"𝑔",h:"𝒽",i:"𝒾",j:"𝒿",k:"𝓀",l:"𝓁",m:"𝓂",n:"𝓃",o:"𝑜",p:"𝓅",q:"𝓆",r:"𝓇",s:"𝓈",t:"𝓉",u:"𝓊",v:"𝓋",w:"𝓌",x:"𝓍",y:"𝓎",z:"𝓏",A:"𝒜",B:"ℬ",C:"𝒞",D:"𝒟",E:"ℰ",F:"ℱ",G:"𝒢",H:"ℋ",I:"ℐ",J:"𝒥",K:"𝒦",L:"ℒ",M:"ℳ",N:"𝒩",O:"𝒪",P:"𝒫",Q:"𝒬",R:"ℛ",S:"𝒮",T:"𝒯",U:"𝒰",V:"𝒱",W:"𝒲",X:"𝒳",Y:"𝒴",Z:"𝒵" } },
        { name: "love_heart_3", prefix: "💕 ", suffix: " 💕", map: { a:"𝕒",b:"𝕓",c:"𝕔",d:"𝕕",e:"𝕖",f:"𝕗",g:"𝕘",h:"𝕙",i:"𝕚",j:"𝕛",k:"𝕜",l:"𝕝",m:"𝕞",n:"𝕟",o:"𝕠",p:"𝕡",q:"𝕢",r:"𝕣",s:"𝕤",t:"𝕥",u:"𝕦",v:"𝕧",w:"𝕨",x:"𝕩",y:"𝕪",z:"𝕫",A:"𝔸",B:"𝔹",C:"ℂ",D:"𝔻",E:"𝔼",F:"𝔽",G:"𝔾",H:"ℍ",I:"𝕀",J:"𝕁",K:"𝕂",L:"𝕃",M:"𝕄",N:"ℕ",O:"𝕆",P:"ℙ",Q:"ℚ",R:"ℝ",S:"𝕊",T:"𝕋",U:"𝕌",V:"𝕍",W:"𝕎",X:"𝕏",Y:"𝕐",Z:"ℤ" } },
        { name: "love_angel_style", prefix: "😇 ", suffix: " 😇", map: { a:"α",b:"ß",c:"¢",d:"Ð",e:"ε",f:"ƒ",g:"g",h:"н",i:"ι",j:"נ",k:"к",l:"ℓ",m:"м",n:"η",o:"σ",p:"ρ",q:"q",r:"я",s:"ѕ",t:"т",u:"υ",v:"ν",w:"ω",x:"χ",y:"у",z:"z",A:"A",B:"B",C:"C",D:"D",E:"E",F:"F",G:"G",H:"H",I:"I",J:"J",K:"K",L:"L",M:"M",N:"N",O:"O",P:"P",Q:"Q",R:"R",S:"S",T:"T",U:"U",V:"V",W:"W",X:"X",Y:"Y",Z:"Z" } },
        { name: "bold_love_style", prefix: "—͟͞͞✰", suffix: "ᯓ✈︎⋆ˎˊ˗", map: { a:"𝗮",b:"𝗯",c:"𝗰",d:"𝗱",e:"𝗲",f:"𝗳",g:"𝗴",h:"𝗵",i:"𝗶",j:"𝗷",k:"𝗸",l:"𝗹",m:"𝗺",n:"𝗻",o:"𝗼",p:"𝗽",q:"𝗾",r:"𝗿",s:"𝘀",t:"𝘁",u:"𝘂",v:"𝘃",w:"𝘄",x:"𝘅",y:"𝘆",z:"𝘇",A:"𝗔",B:"𝗕",C:"𝗖",D:"𝗗",E:"𝗘",F:"𝗙",G:"𝗚",H:"𝗛",I:"𝗜",J:"𝗝",K:"𝗞",L:"𝗟",M:"𝗠",N:"𝗡",O:"𝗢",P:"𝗣",Q:"𝗤",R:"𝗥",S:"𝗦",T:"𝗧",U:"𝗨",V:"𝗩",W:"𝗪",X:"𝗫",Y:"𝗬",Z:"𝗭" } },
        // ... (आपके original script.js से बाकी 100+ love styles यहाँ आएँगे)
        // मैंने सिर्फ पहले 5 दिखाए हैं – आप अपना पूरा block paste करें
    ],
    gamer: [
        { name: "gamer_bold_style", prefix: "🎮 ", suffix: " 🎮", map: { a:"🅐",b:"🅑",c:"🅒",d:"🅓",e:"🅔",f:"🅕",g:"🅖",h:"🅗",i:"🅘",j:"🅙",k:"🅚",l:"🅛",m:"🅜",n:"🅝",o:"🅞",p:"🅟",q:"🅠",r:"🅡",s:"🅢",t:"🅣",u:"🅤",v:"🅥",w:"🅦",x:"🅧",y:"🅨",z:"🅩",A:"🅐",B:"🅑",C:"🅒",D:"🅓",E:"🅔",F:"🅕",G:"🅖",H:"🅗",I:"🅘",J:"🅙",K:"🅚",L:"🅛",M:"🅜",N:"🅝",O:"🅞",P:"🅟",Q:"🅠",R:"🅡",S:"🅢",T:"🅣",U:"🅤",V:"🅥",W:"🅦",X:"🅧",Y:"🅨",Z:"🅩" } },
        { name: "gamer_monospace_style", prefix: "🔥 ", suffix: " 🔥", map: { a:"𝚊",b:"𝚋",c:"𝚌",d:"𝚍",e:"𝚎",f:"𝚏",g:"𝚐",h:"𝚑",i:"𝚒",j:"𝚓",k:"𝚔",l:"𝚕",m:"𝚖",n:"𝚗",o:"𝚘",p:"𝚙",q:"𝚚",r:"𝚛",s:"𝚜",t:"𝚝",u:"𝚞",v:"𝚟",w:"𝚠",x:"𝚡",y:"𝚢",z:"𝚣",A:"𝙰",B:"𝙱",C:"𝙲",D:"𝙳",E:"𝙴",F:"𝙵",G:"𝙶",H:"𝙷",I:"𝙸",J:"𝙹",K:"𝙺",L:"𝙻",M:"𝙼",N:"𝙽",O:"𝙾",P:"𝙿",Q:"𝚀",R:"𝚁",S:"𝚂",T:"𝚃",U:"𝚄",V:"𝚅",W:"𝚆",X:"𝚇",Y:"𝚈",Z:"𝚉" } },
        { name: "gamer_danger_style", prefix: "💀 ", suffix: " 💀", map: { a:"ค",b:"๖",c:"¢",d:"໓",e:"ē",f:"f",g:"ງ",h:"h",i:"i",j:"ว",k:"k",l:"l",m:"๓",n:"ຖ",o:"໐",p:"p",q:"๑",r:"r",s:"Ş",t:"t",u:"น",v:"ง",w:"ຟ",x:"x",y:"ฯ",z:"ຊ",A:"ค",B:"๖",C:"¢",D:"໓",E:"ē",F:"f",G:"ງ",H:"h",I:"i",J:"ว",K:"k",L:"l",M:"๓",N:"ຖ",O:"໐",P:"p",Q:"๑",R:"r",S:"Ş",T:"t",U:"น",V:"ง",W:"ຟ",X:"x",Y:"ฯ",Z:"ຊ" } },
        { name: "gamer_skull", prefix: "☠️ ", suffix: " ☠️", map: { a:"Ꮧ",b:"Ᏸ",c:"ፈ",d:"Ꮄ",e:"Ꮛ",f:"Ꭶ",g:"Ꮆ",h:"Ꮒ",i:"Ꭵ",j:"Ꮰ",k:"Ꮶ",l:"Ꮭ",m:"Ꮇ",n:"Ꮑ",o:"Ꭷ",p:"Ꭾ",q:"Ꭴ",r:"Ꮢ",s:"Ꮥ",t:"Ꮦ",u:"Ꮼ",v:"Ꮙ",w:"Ꮗ",x:"ጀ",y:"Ꭹ",z:"ፚ",A:"Ꮧ",B:"Ᏸ",C:"ፈ",D:"Ꮄ",E:"Ꮛ",F:"Ꭶ",G:"Ꮆ",H:"Ꮒ",I:"Ꭵ",J:"Ꮰ",K:"Ꮶ",L:"Ꮭ",M:"Ꮇ",N:"Ꮑ",O:"Ꭷ",P:"Ꭾ",Q:"Ꭴ",R:"Ꮢ",S:"Ꮥ",T:"Ꮦ",U:"Ꮼ",V:"Ꮙ",W:"Ꮗ",X:"ጀ",Y:"Ꭹ",Z:"ፚ" } },
        // ... बाकी gamer styles
    ],
    fancy: [
        { name: "fancy_script", prefix: "👑 ", suffix: " 👑", map: { a:"𝒶",b:"𝒷",c:"𝒸",d:"𝒹",e:"𝑒",f:"𝒻",g:"𝑔",h:"𝒽",i:"𝒾",j:"𝒿",k:"𝓀",l:"𝓁",m:"𝓂",n:"𝓃",o:"𝑜",p:"𝓅",q:"𝓆",r:"𝓇",s:"𝓈",t:"𝓉",u:"𝓊",v:"𝓋",w:"𝓌",x:"𝓍",y:"𝓎",z:"𝓏",A:"𝒜",B:"ℬ",C:"𝒞",D:"𝒟",E:"ℰ",F:"ℱ",G:"𝒢",H:"ℋ",I:"ℐ",J:"𝒥",K:"𝒦",L:"ℒ",M:"ℳ",N:"𝒩",O:"𝒪",P:"𝒫",Q:"𝒬",R:"ℛ",S:"𝒮",T:"𝒯",U:"𝒰",V:"𝒱",W:"𝒲",X:"𝒳",Y:"𝒴",Z:"𝒵" } },
        { name: "fancy_outline", prefix: "✨ ", suffix: " ✨", map: { a:"𝕒",b:"𝕓",c:"𝕔",d:"𝕕",e:"𝕖",f:"𝕗",g:"𝕘",h:"𝕙",i:"𝕚",j:"𝕛",k:"𝕜",l:"𝕝",m:"𝕞",n:"𝕟",o:"𝕠",p:"𝕡",q:"𝕢",r:"𝕣",s:"𝕤",t:"𝕥",u:"𝕦",v:"𝕧",w:"𝕨",x:"𝕩",y:"𝕪",z:"𝕫",A:"𝔸",B:"𝔹",C:"ℂ",D:"𝔻",E:"𝔼",F:"𝔽",G:"𝔾",H:"ℍ",I:"𝕀",J:"𝕁",K:"𝕂",L:"𝕃",M:"𝕄",N:"ℕ",O:"𝕆",P:"ℙ",Q:"ℚ",R:"ℝ",S:"𝕊",T:"𝕋",U:"𝕌",V:"𝕍",W:"𝕎",X:"𝕏",Y:"𝕐",Z:"ℤ" } },
        { name: "fancy_cross", prefix: "✧ ", suffix: " ✧", map: { a:"𝕒",b:"𝕓",c:"𝕔",d:"𝕕",e:"𝕖",f:"𝕗",g:"𝕘",h:"𝕙",i:"𝕚",j:"𝕛",k:"𝕜",l:"𝕝",m:"𝕞",n:"𝕟",o:"𝕠",p:"𝕡",q:"𝕢",r:"𝕣",s:"𝕤",t:"𝕥",u:"𝕦",v:"𝕧",w:"𝕨",x:"𝕩",y:"𝕪",z:"𝕫",A:"𝔸",B:"𝔹",C:"ℂ",D:"𝔻",E:"𝔼",F:"𝔽",G:"𝔾",H:"ℍ",I:"𝕀",J:"𝕁",K:"𝕂",L:"𝕃",M:"𝕄",N:"ℕ",O:"𝕆",P:"ℙ",Q:"ℚ",R:"ℝ",S:"𝕊",T:"𝕋",U:"𝕌",V:"𝕍",W:"𝕎",X:"𝕏",Y:"𝕐",Z:"ℤ" } },
        // ... बाकी fancy styles
    ],
    font: [
        { name: "font_cursive", prefix: "", suffix: "", map: { a:"𝓪",b:"𝓫",c:"𝓬",d:"𝓭",e:"𝓮",f:"𝓯",g:"𝓰",h:"𝓱",i:"𝓲",j:"𝓳",k:"𝓴",l:"𝓵",m:"𝓶",n:"𝓷",o:"𝓸",p:"𝓹",q:"𝓺",r:"𝓻",s:"𝓼",t:"𝓽",u:"𝓾",v:"𝓿",w:"𝔀",x:"𝔁",y:"𝔂",z:"𝔃",A:"𝓐",B:"𝓑",C:"𝓒",D:"𝓓",E:"𝓔",F:"𝓕",G:"𝓖",H:"𝓗",I:"𝓘",J:"𝓙",K:"𝓚",L:"𝓛",M:"𝓜",N:"𝓝",O:"𝓞",P:"𝓟",Q:"𝓠",R:"𝓡",S:"𝓢",T:"𝓣",U:"𝓤",V:"𝓥",W:"𝓦",X:"𝓧",Y:"𝓨",Z:"𝓩" } },
        { name: "font_bubble", prefix: "", suffix: "", map: { a:"ⓐ",b:"ⓑ",c:"ⓒ",d:"ⓓ",e:"ⓔ",f:"ⓕ",g:"ⓖ",h:"ⓗ",i:"ⓘ",j:"ⓙ",k:"ⓚ",l:"ⓛ",m:"ⓜ",n:"ⓝ",o:"ⓞ",p:"ⓟ",q:"ⓠ",r:"ⓡ",s:"ⓢ",t:"ⓣ",u:"ⓤ",v:"ⓥ",w:"ⓦ",x:"ⓧ",y:"ⓨ",z:"ⓩ",A:"Ⓐ",B:"Ⓑ",C:"Ⓒ",D:"Ⓓ",E:"Ⓔ",F:"Ⓕ",G:"Ⓖ",H:"Ⓗ",I:"Ⓘ",J:"Ⓙ",K:"Ⓚ",L:"Ⓛ",M:"Ⓜ",N:"Ⓝ",O:"Ⓞ",P:"Ⓟ",Q:"Ⓠ",R:"Ⓡ",S:"Ⓢ",T:"Ⓣ",U:"Ⓤ",V:"Ⓥ",W:"Ⓦ",X:"Ⓧ",Y:"Ⓨ",Z:"Ⓩ" } },
        { name: "font_smallcaps", prefix: "", suffix: "", map: { a:"ᴀ",b:"ʙ",c:"ᴄ",d:"ᴅ",e:"ᴇ",f:"ғ",g:"ɢ",h:"ʜ",i:"ɪ",j:"ᴊ",k:"ᴋ",l:"ʟ",m:"ᴍ",n:"ɴ",o:"ᴏ",p:"ᴘ",q:"ǫ",r:"ʀ",s:"s",t:"ᴛ",u:"ᴜ",v:"ᴠ",w:"ᴡ",x:"x",y:"ʏ",z:"ᴢ",A:"ᴀ",B:"ʙ",C:"ᴄ",D:"ᴅ",E:"ᴇ",F:"ғ",G:"ɢ",H:"ʜ",I:"ɪ",J:"ᴊ",K:"ᴋ",L:"ʟ",M:"ᴍ",N:"ɴ",O:"ᴏ",P:"ᴘ",Q:"ǫ",R:"ʀ",S:"s",T:"ᴛ",U:"ᴜ",V:"ᴠ",W:"ᴡ",X:"x",Y:"ʏ",Z:"ᴢ" } },
        // ... बाकी font styles
    ]
};

// ============================================
// 2. SUGGESTIONS DATA
// ============================================
let suggestionsData = {
love: [
"𝓛𝓸𝓿𝓮𝓻 l𝓫𝓸𝔂 💕",
"⋆𐙚:͢I:͢L:͢♡:͢V:͢E:͢y:͢o:͢u𓏧𓅚",
"►►❇︎˖°M̶o̶m̶-D̶a̶d̶°˖☂ ‹𝟹",
"𓆩♡𓆪𝐁𝐚𝐛𝐲𝐠𝐢𝐫𝐥𓆩♡𓆪",
"☆꧁☾𝒞𝒽𝑒𝓇𝒾𝓈𝒽𝑒𝒹☽꧂☆",
"𝐃𝐚𝐫𝐥𖧷𝐢𝐧𝐠 ☂",
"C̶u̶t̶i̶e̶ P̶i̶e̶ 💕⃝🕊️",
"𝑃𝑢𝑟𝑒♡𝐿𝑜𝑣𝑒 ☂",
"🍂 ░C░u░t░e░  『』𓅚 ✧",
"♡♡ 𝐍𝐱 𝐝𝐢𝐝𝐮",
"⸝⸝⸝♡⸝⸝⸝ 𝙼 𝙰 𝙷 𝙸⸝⸝⸝♡⸝⸝⸝",
"꧁(✿◠‿◠) Ⓟ Ⓡ Ⓘ Ⓨ Ⓐ ✦",
"៚𝙻𝚘𝚟𝚎𝚋𝚒𝚛𝚍𝚒𝚎𓅫⋆˙⟡",
"ℐ 𝓁ℴ𝓋ℯ 𝓎ℴ𝓊 <3 𝑹 𝑰 𝒀 𝑼",
"💕⃝𝙸 𝙼 𝚂𝚘𝚘 𝚂𝚘𝚛𝚛𝚢 ⋆.🥀",
"Sмιℓє ᶠᵒʳᵉᵛᵉʳ̤̮ ☺︎",
"जय श्री कृष्ण !🪈𓃔",
"˖°Magιc°˖ᴸᴼⱽᴱ",
"ᯓ★ ‼ ️Ꭾʀɪ፝֟ɴᴄᴇㅤᥫ᭡.",
"🐼⃞ᴵᵐ•𝐴 𝑁 𝐼 𝑌 𝐴᭄࿐",
"Ꮯн𖹭ꮯσ Ᏼ𖹭ʏ !! (⁠◠⁠‿⁠◕⁠)",
"𓆩𓆪 ƒ ř ï ř є ռ 𓆩𓆪💕⃝🕊️",
"➶➶ Hᵤ𝓱ᵤ ➷➷",
"ꜱᴛᴀʀ☆ʟᴏᴠᴇʀ𖹭",
"🦋⃟💗᪲᪲᪲мγ нεαяτ⋆.𐙚✨",
"ᴅʀᴇᴀᴍ❇︎ɢ·ɪ·ʀ·ʟ·⋆˙𖹭",
"𓆩𝑆𝑤𝑒𝑒𝑡𓆪 ℎ𝑒𝑎𝑟𝑡₊˚·🦋⃟💗᪲᪲᪲",
"🫒🎍 P A N D A 🐼",
"𝑴𝒂𝒈𝒊𝒄˚⋆˙𝑮𝒊𝒓𝒍𓍯 𐀪𐀪",
"Βαвγ❇︎Ɗσℓℓ⋆˙⟡🧸",
"˙˚ 𓆩♡𓆪 ˚˙ D A S H A ˙˚ 𓆩♡𓆪 ˚˙",
"｡˚⋆ мɪɗηɪɠнτ⋆｡˚☽˚⋆ ℓσνε⋆°•☁︎",
"ℒℴ𝓋ℯ*☆ ℬ𝒾𝓇𝒹💕⃝🕊️",
"🌊 .·:¨Ꮮᴏᴠᴇ¨:·. 💗᪲᪲᪲🌊",
"💕⃝Ꭵ ᶫᵒᵛᵉᵧₒᵤ 𖹭࿐",
"꧁♡ K H U S B U ♡꧂",
"✨✿ ᴋʀɪsᴛɪɴᴀ ꫂ✿ꪶ 🦚",
"♥︎♡♥︎Ꮮɪꜰᴇʟɪɴᴇ ┈┈┈",
"༒ ℒℴνℯ ✤ U Ｍ♡Ｍ ☆࿐",
"✿ ᴍʀ  ʟᴜᴄᴋʏ 亗 ✿",
"᪲᪲᪲𓄋 ℓo͟v͟ꫀ ყoυ .ᐟ🅾",
"ᰔᩚ┊ᴘʟᴀɢᴀㅤ↬ª⸙",
"—͟͞͞★Ꭾ𝚁ɪͷ֟፝ꮯᴇss 𖹭࿐",
"✧══•❁✰🅐🅝🅤✰❁•══✧",
"𓍯𓂃𓏧๕ۣۜZΞUS™亗",
"么NIEL么☹︎",
"🦋⃟𝗣 𝗜 𝗡 𝗞 𝗜⋆˙⟡💗᪲᪲᪲🩹",
"🦋⃟ғ̶ᴇ̶ᴀ̶ʀ̶ʟ̶ᴇ̶s̶s̶ ‼ ١٥٧٤𖹭",
"🖤⃝ʙʟᴀᴄᴋ ғʟᴏᴡᴇʀ⋆｡˚🥀",
"𖹭 Aᴍɪᴛ  亗",
"亗 𝑆𝐀𝐥𝐢𝐧【≽ܫ≼】🧸",
"ẞʟᴀⅽᴋ 🖤Loꪜᴇᴿ᭄ ༒",
"ᴸᴬ♡ꦿ𝑩𝒆𝒔𝒕𝒊𝒂᭄💕⃝💖",
"✿Gᴀ֟፝ʀᴜᴜ螿 ‹𝟹",
"𝑫 𝒆 𝒂 𝒓  𝑿",
"✿Pᴜ֟፝ᴄᴄᴀ⋆⋅☆‹𝟹",
"ᰔᩚ┊ᴛɪᴋᴋɪㅤ↬ª⸙",
"ℓℓ Ꮮᴏᴠᴇ Ｍᴇ 𓆩💗᪲᪲᪲𓆪",
"•𝑄𝑢𝑒𝑒𝑛ꨄ︎",
"💗᪲᪲᪲𝙰𝙺𝚄𝙻𝙰ᶫᵒᵛᵉᵧₒᵤ💗᪲᪲᪲",
"ʜɪɴᴀᴛᴀ(≧ᴗ≦)",
"◦♡°🦋༄ŁΔЯΔ༄🦋°♡◦",
"✿˖°Magιc°˖✿ˡᵒᵛᵉ☂",
"꩜ Ρ σ σ ј α 𓏧 𖹭࿐",
"♡═══ T E J U ═══♡",
"๖ۣۜ Pokémon ๖ۣۜ",
"☁︎𝑴𝒖𝒍𝒂𝒏☂︎☁︎",
"𓆩꩜𓆪𝑳𝒊𝑺𝒉𝒂𝒏𝒈𓆩꩜𓆪🦋",
"𝐃𝐚𝐫𝐥𖧷𝐢𝐧𝐠 ☕︎ˎˊ˗",
"ᴍr͢⋆˙⟡𝘗𝘌𝘙𝘍𝘌𝘊𝘛⋆˙⟡༒⁰⁹",
"🦋͜͢͡𝄟⃝❤Sмιℓє🦅🦋͜͢͡𝄟⃝",
"P͢e͢r͢f͢e͢c͢t͢ ١٥٧٤ ꩜࿐",
"𝐹𝑜𝑟𝑒𝑣𝑒𝑟 么 𝗠𝗶𝗻𝗲 𖹭 ‹𝟾𝟹",
"⧼𖦹⧽ 𝘏𝘦𝘢𝘳𝘵𝘣𝘳𝘦𝘢𝘬𝘦𝘳 ⋆˙𖹭꧂",
"‼🧣🕊️ ᴍ ɪ ᴋ ᴀ s ᴀ 𖹭 ࿐",
"ҩɴ ₊˚𝐶 𝑟 𝑢 𝑠 𝘩 ✿˚₊࿐"
  
],
  
gamer :[
"⚔️ 𝕲𝖆𝖒𝖊𝖗 𝕷𝖔𝖗𝖉 ⚔️",
"▶▶ Ν๏๏ʙ ❔❔",
"ϻ么ᴅ ▶ ϻ☯ɴᴋᴇㄚ",
"Ɠαηנα ☘ ɠαмεя",
"么ҒᴜɴƬɪᴍἔ ・꧂",
"ＤＥＳＩ ＧＡＭＥＲ",
"❥Β Λ Ɗ Μ Λ Ѕ H",
"𓆩♫𓆪✭ 𝚁 𝚘 𝚋 𝚎 𝚛 𝚝𓆩♫𓆪",
"𝗩 ⓔ 𝙭 𝙡 ☂",
"꧁⭒ ʟ E ɢ E ɴ D ✘ ₀₇ ⭒꧂",
"乂 𝕲 𝖍 ☯ 𝖘 𝖙 乂𓃵",
"༒☆ 𝑳 𝒖 𝒇 𝒇 𝒚 ☆࿐❾⓿",
"亗 𓆩𝗜𝗧𝗔𝗖𝗛𝗜𓆪 ✪",
"╰⁔╯ 𝘎 么 𝘔 𝟹 Я ✧࿐",
"亗 N͢ ᴏ F͢ ᴇ ᴀ ʀ °˖꫟",
"» ʜ ፝ᴇ ɴ я ʏ",
"🔥 🄽🄰 🅇_⛧",
"ɪᴍ᭄𝔾 𝕙 𝕠 𝕤 𝕥シ᭄",
"㋚ 𐌱𐌻𐌳 𐍃𐌻𐌽𐍄𐌻_??",
"‼ 𐌶 𐌰 𐍊 𐌹 𐌼 ★ 𝟵𝟵𝟵",
"༄𖣠 ꀘꋬ ꒒ ꀤ ꐞ ꀎ ꁅ ⚡ 𝟯.𝟬",
"亗 𓆩𝗣𝗮𝗶𝗻𓆪 ✪ 𝟬𝟬𝟳",
"𖣠 вατ-мαη 〄",
"ᴬᴷ ☑ ℓ υ ƒ ƒ γ 𖥔∞𖥔",
"᭄ᵀʳⁱᵖˡᵉ⁻ˢʷᵒʳᵈ ꪶ⚔ꫂ",
"༒ 𝙆𝘼𝙉𝙀𝙆𝙄 𝙆𝙀𝙉 𝙏𝙊𝙆𝘼 ༒",
"⓿❽ ĺ υ ċ ƙ γ 𓅆 ᴳ̸ᴬ̸ᴹ̸ᴱ̸ᴿ̸",
"☠︎ Ꭲʀʏ么Aɢᴀɪɴ࿐",
"༒♡°𝙷𝙸𝙽𝙰𝚃𝙰°♡༒",
"Ꭾ𝙿𝙻𝙰𝚈𝙷𝙰𝚁𝙳╰⁔╯",
"꧁༒Sᴋ•Sᴀʙɪʀᴮᴼˢˢ༒꧂",
"ͶØ ⚠ ☧ŖØβLΣ𝐌 ✓",
"〆NOBRU ☂ SCCP",
"꧁✰ƤЅ¥CӇØ✰꧂",
"𝙶𝙶ᴇᴀsʏ︻デ═一",
"𝚂𝚃𝙰𝚁 ✰ 𝙶𝙰𝙼𝙴𝚁 ‼7",
"⊹˚₊✩ Ξ𝐒𝐏𝐄𝐄𝐃 ˚♡",
"〘CEROL〙• Ꭾřο",
"L@st_K!ss ツ",
"𝖎 𝙰𝙼 ᵍᵒᵈ ✔",
"𝐒𝐍1𝐏𝐄𝐑-𝐗 모",
"〆NANDO⁹⁹⁹ツ",
"𓄂ʟᴏʀᴅ Ꭾᴀɪɴ ꫟",
"₣𝙓ㅤP I R E S",
"『BRADOOCK』☠",
"༒ ☯ 𝗧𝗨𝗙𝗔𝗡 ☯ ༒",
"ᴜʙɪᴛᴀ•Ꭾřο 모",
"꧁𒆜𝕂1Ⓝg𒆜꧂",
"𝐊ΛƦ𝐌𝐀 ☘",
"꧁༒𝕂𝕚𝕝𝕝𝕖𝕣༒꧂",
"꧁☯𝗞𝗜𝗡𝗚ツ☯꧂",
"☯ 𝖐𝖎𝖗𝖆 𒆜",
"𝕏 Khalnayak 모",
"༒ Ꭼᴠɪʟ ༒ ꗃ",
"ℓo̶ʀᴅ ⨳ мᴀᴅᴀʀᴀ ⸙",
"𝖑𝖎𝖙𝖊 𝚈𝙰𝙶𝙰𝙼𝙸 ꫟",
"𝕏 𝐓𝐞𝐫𝐫𝐨𝐫 モ",
"꧁ ☣श्री महाकाल☣ ꧂",
"𝐃𝐞𝐬𝐢 ☯ 𝐋𝐞𝐠𝐞𝐧𝐝 モ ꗃ",
"ℓo̶ʀᴅ ⨳ ɢᴏᴋᴜ ⨳♔",
"╰⁔╯яᴏʟᴇx ⓿⓿❼",
"𝑩𝒍𝒂𝒄𝒌𝒔𝒐𝒖𝒍 ??",
"╰⊱𓆩ⓅⒶⓅⒶ𓆪⊰╯",
"╰⊱𓆩ⓂⓄⓂ𓆪⊰╯",
"₊˚⊹♡ 𝖕𝖗𝖎𝖓𝖈𝖊𝖘𝖘 ♡⊹˚₊",
"𓆩𝙺𝙾𝙽𝙰𝙽𓆪",
"ＢｌａｄｅＸ",
"ᵇˡᵃ̸ᶜᵏ᠅V̷̷ᴇɴo̶ᴍ ˣ‿ˣ",
"ʟ๑яᴅ ⨳ Ꭷвɪᴛᴏ ♔࿐",
"𝕯𝖊𝖒𝖔𝖓 𓄂𝕶𝖎𝖓𝖌 么࿐",
"E̷̷νเℓ ꗃ M̷̷Ꭵᥒᴅ 乡",
"ღ 𐌁l๑๑ᴅ፝ꜱ࿐",
"ʟ๑яᴅ𖧷ɪᴛᴀᴄʜɪ ♛",
"៚ɴ ᴀ ʀ υ ᴛ ᴏ ‼ 𝟶𝟿",
"PAIN X3 !",
"⸙모┊ SadX ꫟",
"PʀɪᴍᴇＸ⸙",
"愛4x aimbot ꔪ 모",
"Oɴʟʏㅤz!xuㅤ모",
"Im NoTxz†| 모",
"Tenzoo¿!",
"𝐗 Ꮃᴀʀʀɪᴏʀ 모",
"LA@end",
"모 Zxtraa..?",
"10x...Speedy **",
"𝙱𝙻𝙰𝙲𝙺 ʟ๑яᴅ 么",
"☆⃟𝘿𝙚𝙖𝙩𝙝 𝙕𝙤𝙣𝙚 ∅꧂",
"𝘙 𝘪 𝘨 𝘩 ✓ ┊GAMER ┊꧂",
"K!ll चोर ☫",
"모Zᴇʀᴏ モᴋɪʟʟ ⊹˚₊✩",
"‼ D̶a̶r̶k̶ K̶i̶l̶l̶c̶r̶ ˣ‿ˣ",
"𝙱𝚁๑𝙺𝙴𝙽 ħєяσ ??",
"S!lent ꫟ K̶i̶l̶l̶c̶r̶ ˣ‿ˣ",
"░⋆｡˚Warior-𝕏 ˚｡⋆░",
"乡Silent Ꭾαïռ 亗",
"𝕏 𝙱𝙻𝙰𝙲𝙺 𝕏 ᵇˡᵃ̸ᶜᵏ",
"ɪɴᴠɪɴᴄɪʙʟᴇ ᴡᴀʀʀɪᴏʀ 🛡️"
// ... बाकी gamer suggestions
],
fancy: [
"👑 𝕱𝖆𝖓𝖈𝖞 𝕶𝖎𝖓𝖌 👑",
"❀ P͢𝕒𝕟𝕕𝕒 ⋆｡˚🐼",
"ʟᗩʙᴜ፝ᴛ𝕆",
"᭄ Ɗᴏⳋᴜᴜ ??",
"乂 刀ʀᴀᴄ☯࿐",
"༒卄ᴀᴊᴋⳕⳕ 𓍯😜",
"Ͻя🅰️ƶㄚ ƓαM⃤乇я𓏧𖹭࿐",
"😝 Ρh𝗬ϽhᎧ き",
"ᴥ 🅿️ʜʏᴄʜ💋 ѕ꒸ʀ 『』",
"么ϻᴀᴅ🎒ϻ𝑬ϻ",
"亗 丂ᴛᴜᴅ𝙴ɴ丅 ˚｡⋆✿",
"Ոᴏ 乂 ѕ੮ᴜ𝖽ʏ₊˚⊹ 📚",
"ᑕʀᴀᴢʏ✨ᑕʟᴀѕѕ 모",
"꧁༒ ✗ 𝚁 𝙾 𝚈 𝙴 𝙻 ✗✨࿐",
"⚠ D• A• V• I• D• 🚬",
"𝙸𝚝𝚣𝚣𝚣_⊹ ࣪𝙼 𝚘 𝚑 𝚊 𝚖 𝚊 𝚍▼_ꪎ👿ꪎ",
"✨ ꧁༒☬𝓕𝓪𝓷𝓬𝔂☬༒꧂ ✨",
"💎 ʟᴜxᴜʀʏ ʟɪғᴇ",
"xX_RAYYAN_Xx",
"༺HA༒NIA༻",
"🧛‍♂️ 𝔇𝔞𝔫𝔦𝔰𝔥",
"🖤 🅐🅗🅜🅔🅓",
"🩸 A̷h̷m̷e̷d̷",
"🔮 ℤ𝕒𝕚𝕟",
"➵N̷i̷g̷h̷t̷𓄂S̷h̷a̷d̷e̷ꪶ乡"
// ... बाकी fancy suggestions
],
font: [
"W⚠️RNING",
"‼ Κ α ɪ ☂",
"𝔊𝔬𝔱𝔥𝔦𝔠 𝔖𝔱𝔶𝔩𝔢",
"ᝰ 𝘢 𝘷 𝘦",
"𝘚𝘗ΞΞ𝘋",
"ꫝυяα",
"𝙶 ⌔𝚕 𝚍",
"✄⌁C┈U┈T⌁",
"𝑾 𝒂 ϟ 𝒕",
"𝘉 ⧉ 𝘟",
"L 𖹭 v e",
"𓄂𝐾 𝑖 𝑛 𝑔",
"ꜱ ᴛ ★ ʀ",
"𓆩ⓌⒾⓃⒼⓈ𓆪",
"△ 𝘕 𝘎 𝘌 𝘓",
"ʟ𖦹𖦹ᴘ",
"𝑹 ⟡ 𝒀 𝑨 𝑳",
"ʜ 𓂋 ʟ",
"ᴜ·ᴍ·☂ʀ·ᴇ·ʟ·ʟ·ᴀ·",
"S i n g 𐀪 e",
"匚卄丨几乇丂乇",
"W͢ a͢ ⌲ V͢ e͢",
"Μ Λ Ɠ Ν ⋐ Τ",
"ꜱ ᴛ ⏱ ᴘ",
"𝑪 𐚁 𝒘 𝑩 𝒐 𝒚",
"𝙈 𝙤☽ 𝙤☽ 𝙣",
"Ή ☺︎ Ρ Ρ Υ",
"𐌱 𓄯 𐍂 𐌽",
"𝑩 𖤛 𖤛 𝑴",
"𝑅 ⸙ 𝑐 𝑒",
"𓃠 𝚗 𝚒 𝚖 𝚊 𝚕",
"ᵈ ◦ ᵃ ᵗ",
"ꫝυяα",
"ᑕOᑌTᕼ ᖴOᑎT",
// ... बाकी font suggestions
]
};

// ============================================
// 3. SYMBOLS DATA
// ============================================
let symbolsData = {
faces: [
{ symbol:"☺", name:"Smiling Face" },
{ symbol:"😊", name:"Blushing Face" },
{ symbol:"😎", name:"Cool Face" },
{ symbol:"☃︎", name:"Snowman" },
{ symbol:"𔓎", name:"Egyptian Decoration" },
{ symbol:"🐼", name:"Panda Face" },
{ symbol:"୧⍤⃝💐", name:"Raising Hand with Flower" },
{ symbol:"๑˃̵ᴗ˂̵๑", name:"Cute Blush Face" },
{ symbol:"⟡‿⟡", name:"Star Eyes Face" },
{ symbol:"̤̮", name:"Combining Breve" },
{ symbol:"×᷼×ㅤ", name:"Crossed Eyes Face" },
{ symbol:"•͜•", name:"Simple Face" },
{ symbol:"𓅫", name:"Egyptian Bird" },
{ symbol:"𓃠", name:"Egyptian Cat" },
{ symbol:"☻", name:"Black Smiling Face" },
{ symbol:"☹︎", name:"Frowning Face" },
{ symbol:":)", name:"Classic Smiley" },
{ symbol:"⑆", name:"Bracket Symbol" },
{ symbol:"╰⁔╯", name:"Bird Face" },
{ symbol:"՞•ㅅ•՞", name:"Curious Face" },
{ symbol:"˃ᴗ˂", name:"Happy Face" },
{ symbol:"≽^•⩊•^≼", name:"Cat Face" },
{ symbol:"(✿◠‿◠)", name:"Flower Face" },
{ symbol:"♥‿♥", name:"Heart Eyes" },
{ symbol:"(˘❥˘)", name:"Kissy Face" },
{ symbol:"(｡◕‿◕｡)", name:"Shiny Happy Face" },
{ symbol:"(๑˃ᴗ˂)", name:"Cute Happy Face" },
// ... बाकी faces
],
gaming: [
{ symbol:"🎮", name:"Game Controller" },
{ symbol:"⚔️", name:"Crossed Swords" },
{ symbol:"🛡️", name:"Shield" },
{ symbol:"☠", name:"Skull" },
{ symbol:"࿐", name:"Flower Swirl" },
{ symbol:"☯", name:"Yin Yang" },
{ symbol:"모", name:"Korean Character" },
{ symbol:"☂", name:"Umbrella" },
{ symbol:"ⓥ", name:"Circled V" },
{ symbol:"𖹭", name:"Ethiopic Syllable" },
{ symbol:"么", name:"Chinese Character" },
{ symbol:"✓", name:"Check Mark" },
{ symbol:"☫", name:"Farsi Symbol" },
{ symbol:"☬", name:"Adi Shakti" },
{ symbol:"『", name:"Left Corner Bracket" },
{ symbol:"』", name:"Right Corner Bracket" },
{ symbol:"༒", name:"Tibetan Sign" },
{ symbol:"☠", name:"Skull and Crossbones" },
{ symbol:"メ", name:"Japanese Character" },
{ symbol:"𐚁", name:"Cypriot Syllable" },
{ symbol:"♡", name:"Heart" },
{ symbol:"乂", name:"Chinese Character Yi" },
{ symbol:"✔", name:"Heavy Check Mark" },
{ symbol:"☺︎", name:"Smiling Face" },
{ symbol:"✗", name:"Ballot X" },
{ symbol:"✰", name:"Star" },
{ symbol:"✞", name:"Cross of Jerusalem" },
{ symbol:"☕︎", name:"Coffee" },
{ symbol:"✌︎︎", name:"Victory Hand" },
{ symbol:"𖦹", name:"Ophiuchus" },
{ symbol:"×͜×", name:"Face Mark" },
{ symbol:"⁹⁹⁹", name:"Number 999" },
{ symbol:"𓆩", name:"Egyptian Vase Left" },
{ symbol:"♫", name:"Music Note" },
{ symbol:"╰⁔╯", name:"Bird" },
{ symbol:"𓆪", name:"Egyptian Vase Right" },
{ symbol:"⧉", name:"Double Square" },
{ symbol:"☆", name:"White Star" },
{ symbol:"⨳", name:"Triple Asterisk" },
{ symbol:"⟆", name:"Sigmoid" },
{ symbol:"ૐ", name:"Om Symbol" },
{ symbol:"ꪶꫂ", name:"Tai Tham" },
{ symbol:"♛", name:"Black Chess Queen" },
{ symbol:"‼", name:"Double Exclamation" },
{ symbol:"ꫝ", name:"Tai Tham" },
{ symbol:"亗", name:"Samurai" },
{ symbol:"❀", name:"White Flower" },
{ symbol:"☛", name:"Right Pointer" },
{ symbol:"⇝", name:"Right Wave Arrow" },
{ symbol:"⇜", name:"Left Wave Arrow" },
{ symbol:"𖤍", name:"Cross Mark" },
{ symbol:"⚠", name:"Warning Sign" },
{ symbol:"⏱", name:"Stopwatch" },
{ symbol:"༄", name:"Tibetan" },
{ symbol:"✿", name:"Black Flower" },
{ symbol:"★", name:"Black Star" },
{ symbol:"㋚", name:"Smiley Face" },
{ symbol:"ϟ", name:"Greek Letter" },
{ symbol:"⚐", name:"White Flag" },
{ symbol:"𐀪", name:"Linear A" },
{ symbol:"᭄", name:"Balinese" },
{ symbol:"☸", name:"Wheel of Dharma" },
{ symbol:"⎈", name:"Helm Symbol" },
{ symbol:"⁍", name:"Bullet" },
{ symbol:"៚", name:"Khmer Sign" },
{ symbol:"7ꪎ", name:"Tai Tham Number" },
{ symbol:"ᯤ", name:"Batak" },
{ symbol:"⊰", name:"Left Right Arrow" },
{ symbol:"⊱", name:"Right Left Arrow" },
{ symbol:"⊹", name:"Hermitian Matrix" },
{ symbol:"╬", name:"Double Cross" },
{ symbol:"˃ᴗ˂", name:"Cute Face" },
{ symbol:":)", name:"Smiley" },
{ symbol:"∞", name:"Infinity" },
{ symbol:"ꪽ", name:"Tai Tham" },
{ symbol:"ꫝ", name:"Tai Tham" },
{ symbol:"Ꭷ", name:"Cherokee" },
{ symbol:"❀", name:"White Flower" },
{ symbol:"᪲᪲᪲", name:"Triple Asterism" },
{ symbol:"𓄋", name:"Egyptian Head" },
{ symbol:"☻", name:"Black Smiley" },
{ symbol:"☁︎", name:"Cloud" },
{ symbol:"ꪎ⁔ꪎ", name:"Tai Tham Design" },
{ symbol:"⚕", name:"Medical Symbol" },
{ symbol:"c̸u̸t̸e̸᭄", name:"Strikethrough Cute" },
// ... बाकी gaming symbols
],
crazy: [
{ symbol: "(⁠θ⁠‿⁠θ⁠)", name: "Crazy Face 1" },
{ symbol: "ʘ⁠‿⁠ʘ", name: "Crazy Face 2" },
{ symbol: "✯⁠ᴗ⁠✯", name: "Crazy Face 3" },
{ symbol: "⊂⁠(⁠◉⁠‿⁠◉⁠)⁠つ", name: "Crazy Face 4" },
{ symbol: "＼⁠(⁠^⁠o⁠^⁠)", name: "Crazy Face 5" },
{ symbol: "୧⁠|⁠ ͡⁠ᵔ⁠ ⁠﹏⁠ ͡⁠ᵔ⁠ ⁠|⁠୨", name: "Crazy Face 6" },
{ symbol: "༼⁠ຈ⁠ل͜⁠ຈ⁠༽", name: "Crazy Face 7" },
{ symbol: "(⁠ ͡⁠°⁠ ͜⁠ʖ⁠ ͡⁠°⁠)", name: "Crazy Face 8" },
{ symbol: "/⁠ᐠ⁠｡⁠ꞈ⁠｡⁠ᐟ⁠", name: "Crazy Face 9" },
{ symbol: "⊙⁠.⁠☉", name: "Crazy Face 10" },
{ symbol: "༼⁠⁰⁠o⁠⁰⁠；⁠༽", name: "Crazy Face 11" },
{ symbol: "(⁠●⁠_⁠_⁠●⁠)", name: "Crazy Face 12" },
{ symbol: "👿", name: "Angry Face with Horns" },
{ symbol: "🤪", name: "Zany Face" },
{ symbol: "🤡", name: "Clown Face" },
{ symbol: "☠︎", name: "Skull" },
{ symbol: "☣︎", name: "Biohazard" },
{ symbol: "☢︎", name: "Radioactive" },
{ symbol: "⚠︎", name: "Warning" },
{ symbol: "⛧", name: "Inverted Pentagram" },
{ symbol: "༒", name: "Cross" },
{ symbol: "༺", name: "Left Decoration" },
{ symbol: "༻", name: "Right Decoration" },
{ symbol: "𖤐", name: "Pentagram" },
{ symbol: "𖤓", name: "Sun Cross" },
{ symbol: "𖣂", name: "Dark Symbol" },
{ symbol: "乂", name: "Cross" },
{ symbol: "〆", name: "Kome" },
{ symbol: "メ", name: "X" },
{ symbol: "么", name: "Small X" },
{ symbol: "彡", name: "Three Strokes" },
{ symbol: "ツ", name: "Smiley" },
{ symbol: "シ", name: "Smiley" },
{ symbol: "々", name: "Iteration Mark" },
{ symbol: "亗", name: "Sheng" },
{ symbol: "࿐", name: "Decoration" },
{ symbol: "᭄", name: "Javanese" },
{ symbol: "꧁", name: "Left Decorative" },
{ symbol: "꧂", name: "Right Decorative" },
{ symbol: "𓆩", name: "Left Wing" },
{ symbol: "𓆪", name: "Right Wing" },
{ symbol: "༗", name: "Decoration" },
{ symbol: "⸸", name: "Cross" },
{ symbol: "⸮", name: "Irony Mark" },
{ symbol: "⸻", name: "Dash" },
{ symbol: "⊹", name: "Decoration" },
{ symbol: "࣪", name: "Dot" },
{ symbol: "♤", name: "Spade" },
{ symbol: "♧", name: "Club" },
{ symbol: "♡", name: "Heart" },
{ symbol: "♢", name: "Diamond" },
{ symbol: "⚜", name: "Fleur-de-lis" },
{ symbol: "❂", name: "Star" },
{ symbol: "❉", name: "Flower" },
{ symbol: "❊", name: "Flower" },
{ symbol: "✤", name: "Star" },
{ symbol: "✥", name: "Star" },
{ symbol: "✣", name: "Star" },
{ symbol: "✢", name: "Star" },
{ symbol: "⚝", name: "Star" },
{ symbol: "⚜", name: "Fleur-de-lis" },
{ symbol: "⚚", name: "Mercury" },
{ symbol: "⚛", name: "Atom" },
{ symbol: "☬", name: "Khanda" },
{ symbol: "☫", name: "Farsi" },
{ symbol: "☯", name: "Yin Yang" },
{ symbol: "☮", name: "Peace" },
{ symbol: "✡", name: "Star of David" },
{ symbol: "☪", name: "Star and Crescent" },
{ symbol: "☘", name: "Shamrock" },
{ symbol: "☠", name: "Skull" },
{ symbol: "☣", name: "Biohazard" },
{ symbol: "☤", name: "Caduceus" },
{ symbol: "☥", name: "Ankh" },
{ symbol: "☦", name: "Cross" },
{ symbol: "☧", name: "Chi Rho" },
{ symbol: "☨", name: "Cross" },
{ symbol: "☩", name: "Cross" },
{ symbol: "☪", name: "Star and Crescent" },
{ symbol: "☫", name: "Farsi" },
{ symbol: "☬", name: "Khanda" },
{ symbol: "★", name: "Black Star" },
{ symbol: "☆", name: "White Star" },
{ symbol: "✪", name: "Star" },
{ symbol: "✯", name: "Star" },
{ symbol: "✰", name: "Star" },
{ symbol: "✵", name: "Star" },
{ symbol: "✶", name: "Star" },
{ symbol: "✷", name: "Star" },
{ symbol: "✸", name: "Star" },
{ symbol: "✹", name: "Star" },
{ symbol: "✺", name: "Star" },
{ symbol: "✻", name: "Star" },
{ symbol: "✼", name: "Star" },
{ symbol: "☏", name: "Telephone" },
{ symbol: "✔", name: "Check Mark" },
{ symbol: "☠︎", name: "Skull" },
{ symbol: "☣︎", name: "Biohazard" },
{ symbol: "☢︎", name: "Radioactive" },
{ symbol: "⚠︎", name: "Warning" },
{ symbol: "𖤐", name: "Pentagram" },
{ symbol: "𖤓", name: "Sun Cross" },
{ symbol: "〆", name: "Kome" },
{ symbol: "ツ", name: "Smiley" },
{ symbol: "シ", name: "Smiley" },
{ symbol: "々", name: "Iteration Mark" },
{ symbol: "᭄", name: "Javanese" },
{ symbol: "乂", name: "Cross" },
{ symbol: "メ", name: "X" },
{ symbol: "么", name: "Small X" },
{ symbol: "彡", name: "Three Strokes" },
{ symbol: "亗", name: "Sheng" },
{ symbol: "࿐", name: "Decoration" },
{ symbol: "༒", name: "Cross" }
],
hearts: [
{ symbol:"❤️", name:"Red Heart" },
{ symbol:"💖", name:"Sparkling Heart" },
{ symbol:"💕", name:"Two Hearts" },
{ symbol:"♡", name:"White Heart" },
{ symbol:"♥", name:"Black Heart" },
{ symbol:"❥", name:"Rotated Heavy Heart" },
{ symbol:"❣", name:"Heart Exclamation" },
{ symbol:"ღ", name:"Georgian Heart" },
{ symbol:"✿", name:"Black Flower" },
{ symbol:"❀", name:"White Flower" },
{ symbol:"⋆", name:"Star Operator" },
{ symbol:"✲", name:"Open Center Asterisk" },
{ symbol:"❊", name:"Eight Teardrop" },
{ symbol:"ꫂ❁", name:"Tai Tham with Flower" },
{ symbol:"𖹭", name:"Ethiopic Syllable" },
{ symbol:"☂", name:"Umbrella" },
{ symbol:"❣", name:"Heart Exclamation" },
{ symbol:"❥", name:"Rotated Heart" },
{ symbol:"❦", name:"Floral Heart" },
{ symbol:"💝᪲᪲᪲", name:"Heart with Ribbon Triple" },
{ symbol:"💓᪲᪲", name:"Beating Heart Double" },
{ symbol:"💞᪳᪳᪳", name:"Revolving Heart Triple" },
{ symbol:"ᡣ𐭩", name:"Mongolian Heart" },
{ symbol:"ꨄ︎", name:"Cham Heart" },
{ symbol:"๛", name:"Khmer Heart" },
{ symbol:"𓏌", name:"Egyptian Heart" },
{ symbol:"𖠌", name:"Osmanya Heart" },
{ symbol:"𓆩ᵛ𓆪", name:"Egyptian Vase with V" },
{ symbol:"☔︎︎", name:"Umbrella with Rain" },
{ symbol:"亗", name:"Samurai Heart" },
{ symbol:"♛", name:"Black Chess Queen" },
{ symbol:"♚", name:"Black Chess King" },
// ... बाकी hearts
],
stars: [
{ symbol:"⭐", name:"Star" },
{ symbol:"🌟", name:"Glowing Star" },
{ symbol:"✨", name:"Sparkles" },
{ symbol:"✪", name:"Circled White Star" },
{ symbol:"★", name:"Black Star" },
{ symbol:"✦", name:"Black Star Small" },
{ symbol:"✧", name:"White Star Small" },
{ symbol:"✩", name:"White Star" },
{ symbol:"✫", name:"Open Center Star" },
{ symbol:"✬", name:"Black Center Star" },
{ symbol:"✭", name:"Outlined Star" },
{ symbol:"✮", name:"Bold Outlined Star" },
{ symbol:"✯", name:"Pinwheel Star" },
{ symbol:"✰", name:"Shadowed Star" },
{ symbol:"✱", name:"Heavy Asterisk" },
{ symbol:"✲", name:"Open Center Asterisk" },
{ symbol:"✳", name:"Eight Spoked Asterisk" },
{ symbol:"✴", name:"Eight Point Star" },
{ symbol:"✵", name:"Eight Point Pinwheel" },
{ symbol:"✶", name:"Six Point Star" },
{ symbol:"✷", name:"Eight Point Rectangular" },
{ symbol:"✸", name:"Heavy Eight Point" },
{ symbol:"✹", name:"Twelve Point Star" },
{ symbol:"✺", name:"Sixteen Point Asterisk" },
{ symbol:"✻", name:"Teardrop Asterisk" },
{ symbol:"✼", name:"Open Center Teardrop" },
{ symbol:"✽", name:"Heavy Teardrop" },
{ symbol:"✾", name:"Six Petal Flower" },
{ symbol:"✿", name:"Black Flower" },
{ symbol:"❀", name:"White Flower" },
{ symbol:"❁", name:"Eight Petal Flower" },
{ symbol:"❂", name:"Eight Point Flower" },
{ symbol:"❃", name:"Heavy Eight Point" },
{ symbol:"❅", name:"Snowflake" },
{ symbol:"❆", name:"Heavy Snowflake" },
{ symbol:"❇", name:"Sparkle" },
{ symbol:"❈", name:"Heavy Sparkle" },
{ symbol:"❉", name:"Balloon Sparkle" },
{ symbol:"❊", name:"Eight Teardrop" },
{ symbol:"❋", name:"Heavy Eight Teardrop" },
{ symbol:"❖", name:"Black Diamond" },
{ symbol:"❘", name:"Light Vertical Bar" },
{ symbol:"❙", name:"Medium Vertical Bar" },
{ symbol:"❚", name:"Heavy Vertical Bar" },
{ symbol:"❛", name:"Left Quote Mark" },
{ symbol:"❜", name:"Right Quote Mark" },
{ symbol:"❝", name:"Double Left Quote" },
{ symbol:"❞", name:"Double Right Quote" },
{ symbol:"❡", name:"Curved Quote" },
{ symbol:"❢", name:"Exclamation Mark" },
{ symbol:"❣", name:"Heart Exclamation" },
{ symbol:"❥", name:"Heavy Heart" },
{ symbol:"❦", name:"Floral Heart" },
{ symbol:"❧", name:"Rotated Heart" },
{ symbol:"✜", name:"Heavy Maltese Cross" },
{ symbol:"✚", name:"Heavy Greek Cross" },
{ symbol:"✙", name:"Outlined Greek Cross" },
{ symbol:"✘", name:"Heavy Ballot X" },
{ symbol:"✗", name:"Ballot X" },
{ symbol:"✖", name:"Heavy Multiplication" },
{ symbol:"✔", name:"Heavy Check Mark" },
{ symbol:"✕", name:"Multiplication Sign" },
{ symbol:"✍", name:"Writing Hand" },
{ symbol:"✎", name:"Lower Right Pencil" },
{ symbol:"✏", name:"Pencil" },
{ symbol:"✑", name:"Upper Right Pencil" },
{ symbol:"✒", name:"Black Nib" },
{ symbol:"✓", name:"Check Mark" },
{ symbol:"✂", name:"Scissors" },
{ symbol:"✁", name:"Upper Scissors" },
{ symbol:"✃", name:"Lower Scissors" },
{ symbol:"✄", name:"White Scissors" },
{ symbol:"✇", name:"Tape Drive" },
{ symbol:"✈", name:"Airplane" },
{ symbol:"✉", name:"Envelope" },
{ symbol:"☩", name:"Jerusalem Cross" },
{ symbol:"☨", name:"Cross of Lorraine" },
{ symbol:"☦", name:"Orthodox Cross" },
{ symbol:"☫", name:"Farsi Symbol" },
{ symbol:"☬", name:"Adi Shakti" },
{ symbol:"☭", name:"Hammer and Sickle" },
{ symbol:"☯", name:"Yin Yang" },
{ symbol:"☽", name:"First Quarter Moon" },
{ symbol:"☾", name:"Last Quarter Moon" },
{ symbol:"☄", name:"Comet" },
{ symbol:"☇", name:"Lightning" },
{ symbol:"☈", name:"Thunderstorm" },
{ symbol:"☉", name:"Sun" },
{ symbol:"☊", name:"Ascending Node" },
{ symbol:"☋", name:"Descending Node" },
{ symbol:"☌", name:"Conjunction" },
{ symbol:"☍", name:"Opposition" },
{ symbol:"☏", name:"White Telephone" },
{ symbol:"⚝", name:"Outlined White Star" },
{ symbol:"⚜", name:"Fleur-de-lis" },
{ symbol:"⚚", name:"Staff of Hermes" },
{ symbol:"⚛", name:"Atom Symbol" },
{ symbol:"⚡", name:"High Voltage" },
{ symbol:"☢", name:"Radioactive" },
{ symbol:"☣", name:"Biohazard" },
{ symbol:"⚘", name:"Flower" },
{ symbol:"⚙", name:"Gear" },
{ symbol:"⚔", name:"Crossed Swords" },
{ symbol:"☠", name:"Skull and Crossbones" },
{ symbol:"♤", name:"White Spade" },
{ symbol:"♧", name:"White Club" },
// ... बाकी stars
],
border: [
{ symbol: "『", name: "Left Corner Bracket" },
{ symbol: "』", name: "Right Corner Bracket" },
{ symbol: "「", name: "Left Corner Bracket" },
{ symbol: "」", name: "Right Corner Bracket" },
{ symbol: "【", name: "Left Black Lenticular" },
{ symbol: "】", name: "Right Black Lenticular" },
{ symbol: "〖", name: "Left White Lenticular" },
{ symbol: "〗", name: "Right White Lenticular" },
{ symbol: "〘", name: "Left Double Angle" },
{ symbol: "〙", name: "Right Double Angle" },
{ symbol: "〚", name: "Left Double Square" },
{ symbol: "〛", name: "Right Double Square" },
{ symbol: "꧁", name: "Left Decorative" },
{ symbol: "꧂", name: "Right Decorative" },
{ symbol: "༺", name: "Left Decorative Border" },
{ symbol: "༻", name: "Right Decorative Border" },
{ symbol: "༼", name: "Left Decorative" },
{ symbol: "༽", name: "Right Decorative" },
{ symbol: "༒", name: "Cross Border" },
{ symbol: "𓆩", name: "Left Wing" },
{ symbol: "𓆪", name: "Right Wing" },
{ symbol: "𓂀", name: "Eye" },
{ symbol: "𖤐", name: "Pentagram Border" },
{ symbol: "乂", name: "Cross Border" },
{ symbol: "メ", name: "X Border" },
{ symbol: "〆", name: "Kome Border" },
{ symbol: "亗", name: "Sheng Border" },
{ symbol: "࿐", name: "Decoration Border" },
{ symbol: "〈", name: "Left Angle" },
{ symbol: "〉", name: "Right Angle" },
{ symbol: "《", name: "Left Double Angle" },
{ symbol: "》", name: "Right Double Angle" },
{ symbol: "〔", name: "Left Tortoise Shell" },
{ symbol: "〕", name: "Right Tortoise Shell" },
{ symbol: "╭", name: "Top Left Rounded" },
{ symbol: "╮", name: "Top Right Rounded" },
{ symbol: "╰", name: "Bottom Left Rounded" },
{ symbol: "╯", name: "Bottom Right Rounded" },
{ symbol: "┌", name: "Top Left" },
{ symbol: "┐", name: "Top Right" },
{ symbol: "└", name: "Bottom Left" },
{ symbol: "┘", name: "Bottom Right" },
{ symbol: "├", name: "Left T" },
{ symbol: "┤", name: "Right T" },
{ symbol: "┬", name: "Top T" },
{ symbol: "┴", name: "Bottom T" },
{ symbol: "┼", name: "Cross" },
{ symbol: "╔", name: "Top Left Double" },
{ symbol: "╗", name: "Top Right Double" },
{ symbol: "╚", name: "Bottom Left Double" },
{ symbol: "╝", name: "Bottom Right Double" },
{ symbol: "╠", name: "Left T Double" },
{ symbol: "╣", name: "Right T Double" },
{ symbol: "╦", name: "Top T Double" },
{ symbol: "╩", name: "Bottom T Double" },
{ symbol: "╬", name: "Cross Double" },
{ symbol: "╓", name: "Top Left Double" },
{ symbol: "╖", name: "Top Right Double" },
{ symbol: "╙", name: "Bottom Left Double" },
{ symbol: "╜", name: "Bottom Right Double" },
// ... बाकी border
],
tech: [
{ symbol: "⌘", name: "Command Key" },
{ symbol: "⌥", name: "Option Key" },
{ symbol: "⌦", name: "Delete Right" },
{ symbol: "⌫", name: "Delete Left" },
{ symbol: "⌧", name: "Clear Key" },
{ symbol: "⌨", name: "Keyboard" },
{ symbol: "⌨️", name: "Keyboard" },
{ symbol: "⍟", name: "Star" },
{ symbol: "⍣", name: "Star" },
{ symbol: "⍤", name: "Star" },
{ symbol: "⍥", name: "Star" },
{ symbol: "⍦", name: "Star" },
{ symbol: "⍧", name: "Star" },
{ symbol: "⍨", name: "Star" },
{ symbol: "⍩", name: "Star" },
{ symbol: "⍪", name: "Star" },
{ symbol: "⍫", name: "Star" },
{ symbol: "⍬", name: "Star" },
{ symbol: "␀", name: "Null" },
{ symbol: "␁", name: "Start of Heading" },
{ symbol: "␂", name: "Start of Text" },
{ symbol: "␃", name: "End of Text" },
{ symbol: "␄", name: "End of Transmission" },
{ symbol: "␅", name: "Enquiry" },
{ symbol: "␆", name: "Acknowledge" },
{ symbol: "␇", name: "Bell" },
{ symbol: "␈", name: "Backspace" },
{ symbol: "␉", name: "Tab" },
{ symbol: "␊", name: "Line Feed" },
{ symbol: "␋", name: "Vertical Tab" },
{ symbol: "␌", name: "Form Feed" },
{ symbol: "␍", name: "Carriage Return" },
{ symbol: "␎", name: "Shift Out" },
{ symbol: "␏", name: "Shift In" },
{ symbol: "␐", name: "Data Link Escape" },
{ symbol: "␑", name: "Device Control 1" },
{ symbol: "␒", name: "Device Control 2" },
{ symbol: "␓", name: "Device Control 3" },
{ symbol: "␔", name: "Device Control 4" },
{ symbol: "␕", name: "Negative Acknowledge" },
{ symbol: "␖", name: "Synchronous Idle" },
{ symbol: "␗", name: "End of Transmission Block" },
{ symbol: "␘", name: "Cancel" },
{ symbol: "␙", name: "End of Medium" },
{ symbol: "␚", name: "Substitute" },
{ symbol: "␛", name: "Escape" },
{ symbol: "␜", name: "File Separator" },
{ symbol: "␝", name: "Group Separator" },
{ symbol: "␞", name: "Record Separator" },
{ symbol: "␟", name: "Unit Separator" },
{ symbol: "␠", name: "Space" },
{ symbol: "␡", name: "Delete" },
{ symbol: "⊂", name: "Subset" },
{ symbol: "⊃", name: "Superset" },
{ symbol: "⊄", name: "Not Subset" },
{ symbol: "⊅", name: "Not Superset" },
{ symbol: "⊆", name: "Subset Equal" },
{ symbol: "⊇", name: "Superset Equal" },
{ symbol: "⊈", name: "Not Subset Equal" },
{ symbol: "⊉", name: "Not Superset Equal" },
{ symbol: "⊊", name: "Proper Subset" },
{ symbol: "⊋", name: "Proper Superset" },
{ symbol: "⊌", name: "Multiset" },
{ symbol: "⊍", name: "Multiset" },
{ symbol: "⊎", name: "Multiset" },
{ symbol: "⊏", name: "Square" },
{ symbol: "⊐", name: "Square" },
{ symbol: "⊑", name: "Square" },
{ symbol: "⊒", name: "Square" },
{ symbol: "⊓", name: "Square" },
{ symbol: "⊔", name: "Square" },
{ symbol: "⊕", name: "Circle Plus" },
{ symbol: "⊖", name: "Circle Minus" },
{ symbol: "⊗", name: "Circle Times" },
{ symbol: "⊘", name: "Circle Slash" },
{ symbol: "⊙", name: "Circle Dot" },
{ symbol: "⊚", name: "Circle Ring" },
{ symbol: "⊛", name: "Circle Star" },
{ symbol: "⊜", name: "Circle Equal" },
{ symbol: "⊝", name: "Circle Dash" },
{ symbol: "⊞", name: "Square Plus" },
{ symbol: "⊟", name: "Square Minus" },
{ symbol: "⊠", name: "Square Times" },
{ symbol: "⊡", name: "Square Dot" },
{ symbol: "⊢", name: "Turnstile" },
{ symbol: "⊣", name: "Turnstile" },
{ symbol: "⊤", name: "Top" },
{ symbol: "⊥", name: "Bottom" },
{ symbol: "⊦", name: "Turnstile" },
{ symbol: "⊧", name: "Turnstile" },
{ symbol: "⊨", name: "Turnstile" },
{ symbol: "⊩", name: "Turnstile" },
{ symbol: "⊪", name: "Turnstile" },
{ symbol: "⊫", name: "Turnstile" },
{ symbol: "⊬", name: "Turnstile" },
{ symbol: "⊭", name: "Turnstile" },
{ symbol: "⊮", name: "Turnstile" },
{ symbol: "⊯", name: "Turnstile" },
{ symbol: "⊰", name: "Turnstile" },
{ symbol: "⊱", name: "Turnstile" },
{ symbol: "⊲", name: "Triangle" },
{ symbol: "⊳", name: "Triangle" },
{ symbol: "⊴", name: "Triangle" },
{ symbol: "⊵", name: "Triangle" },
{ symbol: "⊶", name: "Triangle" },
{ symbol: "⊷", name: "Triangle" },
{ symbol: "⊸", name: "Triangle" },
{ symbol: "⊹", name: "Triangle" },
{ symbol: "⊺", name: "Triangle" },
{ symbol: "⊻", name: "Xor" },
{ symbol: "⊼", name: "Nand" },
{ symbol: "⊽", name: "Nor" },
{ symbol: "⊾", name: "Triangle" },
{ symbol: "⊿", name: "Triangle" },
// ... बाकी tech
],
decorative: [
{ symbol:"❄️", name:"Snowflake" },
{ symbol:"🌸", name:"Cherry Blossom" },
{ symbol:"🎀", name:"Ribbon" },
{ symbol:"🌸⃟", name:"Cherry Blossom with Ring" },
{ symbol:"🩷⃟", name:"Pink Heart with Ring" },
{ symbol:"💖⃟", name:"Sparkling Heart with Ring" },
{ symbol:"🌙⃟", name:"Crescent Moon with Ring" },
{ symbol:"⭐⃟", name:"Star with Ring" },
{ symbol:"🪽⃟", name:"Angel Wing with Ring" },
{ symbol:"🎀⃟", name:"Ribbon with Ring" },
{ symbol:"🦋⃟", name:"Butterfly with Ring" },
{ symbol:"🪻", name:"Hyacinth" },
{ symbol:"𖧷", name:"Star Decoration" },
{ symbol:"💗᪲᪲᪲", name:"Growing Heart Triple" },
{ symbol:"𝄟", name:"Musical Decoration" },
{ symbol:"𐙚", name:"Cypriot Decoration" },
{ symbol:"×᷼×ㅤ", name:"Crossed Eyes Face" },
{ symbol:"•͜•", name:"Simple Face" },
{ symbol:"𓅫", name:"Egyptian Bird" },
{ symbol:"𓃠", name:"Egyptian Cat" },
{ symbol:"⛱", name:"Umbrella on Ground" },
{ symbol:"⎚", name:"Clear Key" },
{ symbol:"☻", name:"Black Smiling Face" },
{ symbol:"☹︎", name:"Frowning Face" },
{ symbol:"⌔", name:"Turtle Shell" },
{ symbol:"♨", name:"Hot Springs" },
{ symbol:"🐞⃝", name:"Ladybug with Circle" },
{ symbol:"🐝⃝", name:"Bee with Circle" },
{ symbol:"🐾⃟", name:"Paw Prints with Ring" },
{ symbol:"⚡︎", name:"High Voltage" },
{ symbol:"𓄧", name:"Egyptian Horn" },
{ symbol:"˚", name:"Ring Above" },
{ symbol:"⬅", name:"Left Arrow" },
{ symbol:"☑", name:"Check Box" },
{ symbol:"⊹", name:"Hermitian Matrix" },
{ symbol:"⟲", name:"Counterclockwise Circle Arrow" },
{ symbol:"▶", name:"Play Button" },
{ symbol:"⁰¹", name:"Superscript 01" },
{ symbol:"₊", name:"Subscript Plus" },
{ symbol:"♾", name:"Infinity" },
{ symbol:"⛷", name:"Skier" },
{ symbol:":)", name:"Classic Smiley" },
{ symbol:"⑆", name:"Bracket Symbol" },
{ symbol:"⋆", name:"Star Operator" },
{ symbol:"ꤪꤨꤪ", name:"Rejang Decoration" },
{ symbol:"⁷⁷⁷", name:"Superscript 777" },
{ symbol:"̤̮", name:"Combining Breve" },
{ symbol:".ᐟ", name:"Exclamation Dot" },
{ symbol:"°", name:"Degree Sign" },
{ symbol:"⨳", name:"Triple Asterisk" },
{ symbol:"⌔", name:"Turtle Shell" },
{ symbol:"༘", name:"Tibetan Mark" },
{ symbol:"𖡼", name:"Myanmar Decoration" },
{ symbol:"𖤣", name:"Myanmar Flower" },
{ symbol:"⁰⁶", name:"Superscript 06" },
{ symbol:"𖥧", name:"Myanmar Decoration" },
{ symbol:"𓍊", name:"Egyptian Reed" },
{ symbol:"†", name:"Dagger" },
{ symbol:"⁹⁹⁹", name:"Superscript 999" },
{ symbol:"༝༚༝༚", name:"Tibetan Decoration" },
{ symbol:"⇝", name:"Right Wave Arrow" },
{ symbol:"⇜", name:"Left Wave Arrow" },
{ symbol:"↕", name:"Up Down Arrow" },
{ symbol:"▫", name:"White Small Square" },
{ symbol:"™", name:"Trade Mark" },
{ symbol:"♂", name:"Male Sign" },
{ symbol:"♀", name:"Female Sign" },
{ symbol:"〽", name:"Part Alternation Mark" },
{ symbol:"𓍼", name:"Egyptian Decoration" },
{ symbol:"ྀི", name:"Tibetan Vowel Sign" },
{ symbol:"ᡣ𐭩", name:"Mongolian Decoration" },
{ symbol:"๛", name:"Khmer Decoration" },
{ symbol:"☔︎︎", name:"Umbrella with Rain" },
{ symbol:"⸝⸝", name:"Decoration Dots" },
{ symbol:"∘", name:"Ring Operator" },
{ symbol:"‹𝟹", name:"Left Heart" },
{ symbol:"⚕", name:"Medical Symbol" },
{ symbol:"ꨄ︎", name:"Cham Heart" },
{ symbol:"◌", name:"Dotted Circle" },
{ symbol:"∞", name:"Infinity" },
{ symbol:"⑅", name:"Bracket Decoration" }
// ... बाकी decorative
]
};
